// <auto-generated />
namespace NorthWind2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class orderlist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderlist));
        
        string IMigrationMetadata.Id
        {
            get { return "201504242140133_orderlist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
